require("react-hot-loader/patch")
require("babel-runtime/regenerator")
require("babel-core/register")
require("webpack-hot-middleware/client?reload=true")
require("./main.css")
require("./images/link.jpg")
require("./index.html")
require("./app")
