require("babel-runtime/regenerator")
require("babel-register")
require("webpack-hot-middleware/client?reload=true")
require("./main.sass")
// require("./main.css")
require("./images/link.jpg")
require("./index.ejs")
